package main

import (
	"os"
	"strconv"

	"github.com/ajstarks/deck/generate"
)

type place struct {
	name     string
	distance float64
}

type dt struct {
	name string
	dist []place
}

func main() {

	data := []dt{
		{name: "Beavertown", dist: []place{}},

		{name: "Boonton", dist: []place{
			{name: "Beavertown", distance: 5.3}}},

		{name: "Budds Lake", dist: []place{
			{name: "Beaverton", distance: 21.3},
			{name: "Boonton", distance: 16.0}}},

		{name: "Chatham", dist: []place{
			{name: "Beaverton", distance: 12.2},
			{name: "Boonton", distance: 10.4},
			{name: "Budds Lake", distance: 18.7}}},

		{name: "Chester", dist: []place{
			{name: "Beaverton", distance: 21.4},
			{name: "Boonton", distance: 16.3},
			{name: "Budds Lake", distance: 5.4},
			{name: "Chatham", distance: 15.1}}},

		{name: "Denville", dist: []place{
			{name: "Beaverton", distance: 8.6},
			{name: "Boonton", distance: 3.3},
			{name: "Budds Lake", distance: 12.7},
			{name: "Chatham", distance: 10.5},
			{name: "Chester", distance: 13.0}}},

		{name: "Dover", dist: []place{
			{name: "Beaverton", distance: 12.8},
			{name: "Boonton", distance: 7.5},
			{name: "Budds Lake", distance: 8.5},
			{name: "Chatham", distance: 12.4},
			{name: "Chester", distance: 9.3},
			{name: "Denville", distance: 4.1}}},

		{name: "Drakestown", dist: []place{
			{name: "Beaverton", distance: 23.8},
			{name: "Boonton", distance: 18.5},
			{name: "Budds Lake", distance: 2.6},
			{name: "Chatham", distance: 20.5},
			{name: "Chester", distance: 5.5},
			{name: "Denville", distance: 15.2},
			{name: "Dover", distance: 11.1}}},

		{name: "Flanders", dist: []place{
			{name: "Beaverton", distance: 19.7},
			{name: "Boonton", distance: 14.4},
			{name: "Budds Lake", distance: 2.2},
			{name: "Chatham", distance: 16.5},
			{name: "Chester", distance: 3.9},
			{name: "Denville", distance: 11.1},
			{name: "Dover", distance: 7.0},
			{name: "Drakestown", distance: 4.2}}},

		{name: "German Valley", dist: []place{
			{name: "Beaverton", distance: 2.5},
			{name: "Boonton", distance: 19.2},
			{name: "Budds Lake", distance: 5.6},
			{name: "Chatham", distance: 19.8},
			{name: "Chester", distance: 1.1},
			{name: "Denville", distance: 16.6},
			{name: "Dover", distance: 12.6},
			{name: "Drakestown", distance: 3.7},
			{name: "Flanders", distance: 5.9}}},

		{name: "Green Village", dist: []place{
			{name: "Beaverton", distance: 13.8},
			{name: "Boonton", distance: 10.8},
			{name: "Budds Lake", distance: 15.3},
			{name: "Chatham", distance: 3.3},
			{name: "Chester", distance: 12.5},
			{name: "Denville", distance: 9.8},
			{name: "Dover", distance: 10.5},
			{name: "Drakestown", distance: 11.4},
			{name: "Flanders", distance: 13.6},
			{name: "German Valley", distance: 16.6}}},

		{name: "Hackettstown", dist: []place{
			{name: "Beaverton", distance: 26.1},
			{name: "Boonton", distance: 20.9},
			{name: "Budds Lake", distance: 4.9},
			{name: "Chatham", distance: 22.8},
			{name: "Chester", distance: 7.4},
			{name: "Denville", distance: 17.6},
			{name: "Dover", distance: 13.4},
			{name: "Drakestown", distance: 2.4},
			{name: "Flanders", distance: 6.7},
			{name: "German Valley", distance: 4.2},
			{name: "Green Village", distance: 19.6}}},

		{name: "Hanover", dist: []place{
			{name: "Beaverton", distance: 8.3},
			{name: "Boonton", distance: 6.1},
			{name: "Budds Lake", distance: 18.2},
			{name: "Chatham", distance: 4.0},
			{name: "Chester", distance: 16.2},
			{name: "Denville", distance: 7.6},
			{name: "Dover", distance: 10.5},
			{name: "Drakestown", distance: 20.3},
			{name: "Flanders", distance: 15.0},
			{name: "German Valley", distance: 20.4},
			{name: "Green Village", distance: 5.8},
			{name: "Hackettstown", distance: 22.7}}},

		{name: "Hibernia", dist: []place{
			{name: "Beaverton", distance: 9.1},
			{name: "Boonton", distance: 4.7},
			{name: "Budds Lake", distance: 13.1},
			{name: "Chatham", distance: 14.0},
			{name: "Chester", distance: 14.8},
			{name: "Denville", distance: 3.6},
			{name: "Dover", distance: 5.5},
			{name: "Drakestown", distance: 15.7},
			{name: "Flanders", distance: 12.0},
			{name: "German Valley", distance: 17.8},
			{name: "Green Village", distance: 13.4},
			{name: "Hackettstown", distance: 18.2},
			{name: "Hanover", distance: 10.9}}},

		{name: "Hurdtown", dist: []place{
			{name: "Beaverton", distance: 14.0},
			{name: "Boonton", distance: 9.4},
			{name: "Budds Lake", distance: 9.9},
			{name: "Chatham", distance: 17.4},
			{name: "Chester", distance: 13.2},
			{name: "Denville", distance: 7.2},
			{name: "Dover", distance: 5.6},
			{name: "Drakestown", distance: 12.5},
			{name: "Flanders", distance: 9.6},
			{name: "German Valley", distance: 15.3},
			{name: "Green Village", distance: 16.0},
			{name: "Hackettstown", distance: 14.4},
			{name: "Hanover", distance: 14.9},
			{name: "Hiberbia", distance: 4.9}}},

		{name: "Madison", dist: []place{
			{name: "Beaverton", distance: 11.9},
			{name: "Boonton", distance: 9.4},
			{name: "Budds Lake", distance: 16.8},
			{name: "Chatham", distance: 1.8},
			{name: "Chester", distance: 14.0},
			{name: "Denville", distance: 9.0},
			{name: "Dover", distance: 10.5},
			{name: "Drakestown", distance: 18.6},
			{name: "Flanders", distance: 14.7},
			{name: "German Valley", distance: 18.1},
			{name: "Green Village", distance: 2.0},
			{name: "Hackettstown", distance: 20.9},
			{name: "Hanover", distance: 3.7},
			{name: "Hiberbia", distance: 12.7},
			{name: "Hurdtown", distance: 15.7}}},

		{name: "Mendham", dist: []place{
			{name: "Beaverton", distance: 17.8},
			{name: "Boonton", distance: 12.9},
			{name: "Budds Lake", distance: 8.4},
			{name: "Chatham", distance: 11.1},
			{name: "Chester", distance: 4.5},
			{name: "Denville", distance: 10.1},
			{name: "Dover", distance: 7.5},
			{name: "Drakestown", distance: 9.6},
			{name: "Flanders", distance: 6.3},
			{name: "German Valley", distance: 8.7},
			{name: "Green Village", distance: 7.9},
			{name: "Hackettstown", distance: 11.8},
			{name: "Hanover", distance: 11.9},
			{name: "Hiberbia", distance: 12.7},
			{name: "Hurdtown", distance: 12.6},
			{name: "Madison", distance: 9.4}}},

		{name: "Milton", dist: []place{
			{name: "Beavertown", distance: 11.9},
			{name: "Boonton", distance: 8.9},
			{name: "Budds Lake", distance: 14.6},
			{name: "Chatham", distance: 18.7},
			{name: "Chester", distance: 17.6},
			{name: "Denville", distance: 8.3},
			{name: "Dover", distance: 9.0},
			{name: "Drakestown", distance: 17.1},
			{name: "Flanders", distance: 14.2},
			{name: "German Valley", distance: 19.9},
			{name: "Green Village", distance: 18.1},
			{name: "Hackettstown", distance: 19.1},
			{name: "Hanover", distance: 15.4},
			{name: "Hibernia", distance: 4.6},
			{name: "Hurdtown", distance: 4.7},
			{name: "Madison", distance: 17.3},
			{name: "Mendham", distance: 16.4}}},

		{name: "Montville", dist: []place{
			{name: "Beavertown", distance: 3.2},
			{name: "Boonton", distance: 2.2},
			{name: "Budds Lake", distance: 18.1},
			{name: "Chatham", distance: 11.5},
			{name: "Chester", distance: 18.4},
			{name: "Denville", distance: 5.5},
			{name: "Dover", distance: 9.6},
			{name: "Drakestown", distance: 20.7},
			{name: "Flanders", distance: 16.6},
			{name: "German Valley", distance: 22.1},
			{name: "Green Village", distance: 12.4},
			{name: "Hackettstown", distance: 23.0},
			{name: "Hanover", distance: 7.6},
			{name: "Hibernia", distance: 6.0},
			{name: "Hurdtown", distance: 10.9},
			{name: "Madison", distance: 10.8},
			{name: "Mendham", distance: 15.1},
			{name: "Milton", distance: 9.3}}},

		{name: "Morristown", dist: []place{
			{name: "Beavertown", distance: 11.7},
			{name: "Boonton", distance: 7.6},
			{name: "Budds Lake", distance: 13.1},
			{name: "Chatham", distance: 5.8},
			{name: "Chester", distance: 10.3},
			{name: "Denville", distance: 6.0},
			{name: "Dover", distance: 6.6},
			{name: "Drakestown", distance: 15.0},
			{name: "Flanders", distance: 10.9},
			{name: "German Valley", distance: 15.0},
			{name: "Green Village", distance: 4.0},
			{name: "Hackettstown", distance: 17.4},
			{name: "Hanover", distance: 5.4},
			{name: "Hibernia", distance: 9.6},
			{name: "Hurdtown", distance: 12.0},
			{name: "Madison", distance: 4.0},
			{name: "Mendham", distance: 6.5},
			{name: "Milton", distance: 14.2},
			{name: "Montville", distance: 9.5}}},

		{name: "New Vernon", dist: []place{
			{name: "Beavertown", distance: 14.8},
			{name: "Boonton", distance: 11.0},
			{name: "Budds Lake", distance: 13.6},
			{name: "Chatham", distance: 5.7},
			{name: "Chester", distance: 10.1},
			{name: "Denville", distance: 9.3},
			{name: "Dover", distance: 9.1},
			{name: "Drakestown", distance: 15.1},
			{name: "Flanders", distance: 11.4},
			{name: "German Valley", distance: 14.2},
			{name: "Green Village", distance: 2.4},
			{name: "Hackettstown", distance: 17.3},
			{name: "Hanover", distance: 7.4},
			{name: "Hibernia", distance: 12.8},
			{name: "Hurdtown", distance: 14.7},
			{name: "Madison", distance: 4.1},
			{name: "Mendham", distance: 5.5},
			{name: "Milton", distance: 17.3},
			{name: "Montville", distance: 12.9},
			{name: "Morristown", distance: 3.4}}},

		{name: "Parsippany", dist: []place{
			{name: "Beavertown", distance: 9.6},
			{name: "Boonton", distance: 2.5},
			{name: "Budds Lake", distance: 15.5},
			{name: "Chatham", distance: 8.0},
			{name: "Chester", distance: 15.0},
			{name: "Denville", distance: 3.3},
			{name: "Dover", distance: 7.1},
			{name: "Drakestown", distance: 17.9},
			{name: "Flanders", distance: 13.7},
			{name: "German Valley", distance: 18.8},
			{name: "Green Village", distance: 4.3},
			{name: "Hackettstown", distance: 20.4},
			{name: "Hanover", distance: 4.6},
			{name: "Hibernia", distance: 6.3},
			{name: "Hurdtown", distance: 10.5},
			{name: "Madison", distance: 7.0},
			{name: "Mendham", distance: 11.25},
			{name: "Milton", distance: 10.8},
			{name: "Montville", distance: 4.2},
			{name: "Morristown", distance: 5.4},
			{name: "New Vernon", distance: 8.7}}},

		{name: "Pompton Plains", dist: []place{
			{name: "Beavertown", distance: 3.4},
			{name: "Boonton", distance: 7.4},
			{name: "Budds Lake", distance: 22.7},
			{name: "Chatham", distance: 15.5},
			{name: "Chester", distance: 23.5},
			{name: "Denville", distance: 10.4},
			{name: "Dover", distance: 14.4},
			{name: "Drakestown", distance: 25.3},
			{name: "Flanders", distance: 21.3},
			{name: "German Valley", distance: 26.9},
			{name: "Green Village", distance: 17.0},
			{name: "Hackettstown", distance: 27.6},
			{name: "Hanover", distance: 11.6},
			{name: "Hibernia", distance: 9.7},
			{name: "Hurdtown", distance: 14.2},
			{name: "Madison", distance: 15.3},
			{name: "Mendham", distance: 20.3},
			{name: "Milton", distance: 11.4},
			{name: "Montville", distance: 5.1},
			{name: "Morristown", distance: 14.6},
			{name: "New Vernon", distance: 17.8},
			{name: "Parsippany", distance: 9.1}}},

		{name: "Port Oram", dist: []place{
			{name: "Beavertown", distance: 13.6},
			{name: "Boonton", distance: 8.4},
			{name: "Budds Lake", distance: 7.7},
			{name: "Chatham", distance: 13.6},
			{name: "Chester", distance: 9.2},
			{name: "Denville", distance: 5.2},
			{name: "Dover", distance: 1.3},
			{name: "Drakestown", distance: 10.2},
			{name: "Flanders", distance: 6.4},
			{name: "German Valley", distance: 12.1},
			{name: "Green Village", distance: 11.7},
			{name: "Hackettstown", distance: 12.6},
			{name: "Hanover", distance: 11.8},
			{name: "Hibernia", distance: 5.7},
			{name: "Hurdtown", distance: 4.8},
			{name: "Madison", distance: 11.9},
			{name: "Mendham", distance: 7.9},
			{name: "Milton", distance: 8.6},
			{name: "Montville", distance: 10.5},
			{name: "Morristown", distance: 7.9},
			{name: "New Vernon", distance: 10.2},
			{name: "Parsippany", distance: 8.3},
			{name: "Pompton Plains", distance: 15.0}}},

		{name: "Rockaway", dist: []place{
			{name: "Beavertown", distance: 10.3},
			{name: "Boonton", distance: 5.0},
			{name: "Budds Lake", distance: 11.0},
			{name: "Chatham", distance: 11.8},
			{name: "Chester", distance: 11.8},
			{name: "Denville", distance: 1.9},
			{name: "Dover", distance: 2.5},
			{name: "Drakestown", distance: 13.5},
			{name: "Flanders", distance: 9.4},
			{name: "German Valley", distance: 15.1},
			{name: "Green Village", distance: 10.6},
			{name: "Hackettstown", distance: 15.9},
			{name: "Hanover", distance: 9.3},
			{name: "Hibernia", distance: 3.4},
			{name: "Hurdtown", distance: 5.6},
			{name: "Madison", distance: 10.2},
			{name: "Mendham", distance: 9.3},
			{name: "Milton", distance: 7.7},
			{name: "Montville", distance: 7.2},
			{name: "Morristown", distance: 6.6},
			{name: "New Vernon", distance: 9.7},
			{name: "Parsippany", distance: 5.2},
			{name: "Pompton Plains", distance: 11.9},
			{name: "Port Oram", distance: 3.3}}},

		{name: "Schooleys Mountain", dist: []place{
			{name: "Beavertown", distance: 26.3},
			{name: "Boonton", distance: 12.0},
			{name: "Budds Lake", distance: 5.8},
			{name: "Chatham", distance: 21.6},
			{name: "Chester", distance: 5.9},
			{name: "Denville", distance: 17.8},
			{name: "Dover", distance: 13.7},
			{name: "Drakestown", distance: 3.3},
			{name: "Flanders", distance: 6.7},
			{name: "German Valley", distance: 1.9},
			{name: "Green Village", distance: 18.4},
			{name: "Hackettstown", distance: 2.7},
			{name: "Hanover", distance: 22.0},
			{name: "Hibernia", distance: 18.7},
			{name: "Hurdtown", distance: 15.7},
			{name: "Madison", distance: 19.9},
			{name: "Mendham", distance: 10.5},
			{name: "Milton", distance: 20.4},
			{name: "Montville", distance: 23.3},
			{name: "Morristown", distance: 16.6},
			{name: "New Vernon", distance: 16.0},
			{name: "Parsippany", distance: 20.2},
			{name: "Pompton Plains", distance: 28.0},
			{name: "Port Oram", distance: 13.0},
			{name: "Rockaway", distance: 16.2}}},

		{name: "Shippenport", dist: []place{
			{name: "Beavertown", distance: 17.4},
			{name: "Boonton", distance: 21.1},
			{name: "Budds Lake", distance: 4.2},
			{name: "Chatham", distance: 16.6},
			{name: "Chester", distance: 7.6},
			{name: "Denville", distance: 8.9},
			{name: "Dover", distance: 4.9},
			{name: "Drakestown", distance: 6.8},
			{name: "Flanders", distance: 3.7},
			{name: "German Valley", distance: 9.4},
			{name: "Green Village", distance: 14.3},
			{name: "Hackettstown", distance: 9.1},
			{name: "Hanover", distance: 15.3},
			{name: "Hibernia", distance: 8.9},
			{name: "Hurdtown", distance: 5.8},
			{name: "Madison", distance: 14.8},
			{name: "Mendham", distance: 8.3},
			{name: "Milton", distance: 10.5},
			{name: "Montville", distance: 14.2},
			{name: "Morristown", distance: 10.8},
			{name: "New Vernon", distance: 12.4},
			{name: "Parsippany", distance: 12.0},
			{name: "Pompton Plains", distance: 18.6},
			{name: "Port Oram", distance: 3.7},
			{name: "Rockaway", distance: 7.1},
			{name: "Schooleys Mountain", distance: 10.0}}},

		{name: "Stanhope", dist: []place{
			{name: "Beavertown", distance: 19.9},
			{name: "Boonton", distance: 14.7},
			{name: "Budds Lake", distance: 2.6},
			{name: "Chatham", distance: 18.8},
			{name: "Chester", distance: 7.5},
			{name: "Denville", distance: 11.5},
			{name: "Dover", distance: 7.4},
			{name: "Drakestown", distance: 4.9},
			{name: "Flanders", distance: 3.6},
			{name: "German Valley", distance: 8.2},
			{name: "Green Village", distance: 16.3},
			{name: "Hackettstown", distance: 6.9},
			{name: "Hanover", distance: 17.7},
			{name: "Hibernia", distance: 11.3},
			{name: "Hurdtown", distance: 7.5},
			{name: "Madison", distance: 17.0},
			{name: "Mendham", distance: 9.5},
			{name: "Milton", distance: 12.2},
			{name: "Montville", distance: 16.7},
			{name: "Morristown", distance: 13.0},
			{name: "New Vernon", distance: 14.2},
			{name: "Parsippany", distance: 14.6},
			{name: "Pompton Plains", distance: 21.0},
			{name: "Port Oram", distance: 6.3},
			{name: "Rockaway", distance: 9.6},
			{name: "Schooleys Mountain", distance: 8.2},
			{name: "Shippenport", distance: 2.5}}},

		{name: "Stephensburgh", dist: []place{
			{name: "Beavertown", distance: 29.4},
			{name: "Boonton", distance: 24.2},
			{name: "Budds Lake", distance: 8.5},
			{name: "Chatham", distance: 24.8},
			{name: "Chester", distance: 9.1},
			{name: "Denville", distance: 20.5},
			{name: "Dover", distance: 16.8},
			{name: "Drakestown", distance: 5.9},
			{name: "Flanders", distance: 9.8},
			{name: "German Valley", distance: 5.0},
			{name: "Green Village", distance: 21.6},
			{name: "Hackettstown", distance: 3.9},
			{name: "Hanover", distance: 25.2},
			{name: "Hibernia", distance: 21.6},
			{name: "Hurdtown", distance: 18.2},
			{name: "Madison", distance: 23.1},
			{name: "Mendham", distance: 13.6},
			{name: "Milton", distance: 22.9},
			{name: "Montville", distance: 26.4},
			{name: "Morristown", distance: 19.9},
			{name: "New Vernon", distance: 19.2},
			{name: "Parsippany", distance: 23.4},
			{name: "Pompton Plains", distance: 31.1},
			{name: "Port Oram", distance: 16.1},
			{name: "Rockaway", distance: 19.2},
			{name: "Schooleys Mountain", distance: 3.2},
			{name: "Shippenport", distance: 12.8},
			{name: "Stanhope", distance: 10.8}}},

		{name: "Succasunny", dist: []place{
			{name: "Beavertown", distance: 16.5},
			{name: "Boonton", distance: 11.2},
			{name: "Budds Lake", distance: 4.9},
			{name: "Chatham", distance: 14.5},
			{name: "Chester", distance: 6.2},
			{name: "Denville", distance: 11.95},
			{name: "Dover", distance: 3.8},
			{name: "Drakestown", distance: 7.3},
			{name: "Flanders", distance: 3.2},
			{name: "German Valley", distance: 8.9},
			{name: "Green Village", distance: 11.9},
			{name: "Hackettstown", distance: 9.7},
			{name: "Hanover", distance: 13.4},
			{name: "Hibernia", distance: 8.9},
			{name: "Hurdtown", distance: 7.1},
			{name: "Madison", distance: 12.6},
			{name: "Mendham", distance: 6.0},
			{name: "Milton", distance: 11.5},
			{name: "Montville", distance: 13.4},
			{name: "Morristown", distance: 8.7},
			{name: "New Vernon", distance: 9.9},
			{name: "Parsippany", distance: 10.7},
			{name: "Pompton Plains", distance: 18.2},
			{name: "Port Oram", distance: 3.2},
			{name: "Rockaway", distance: 6.3},
			{name: "Schooleys Mountain", distance: 9.9},
			{name: "Shippenport", distance: 2.4},
			{name: "Stanhope", distance: 4.4},
			{name: "Stephensburgh", distance: 13.0}}},

		{name: "Walnut Grove", dist: []place{
			{name: "Beavertown", distance: 14.1},
			{name: "Boonton", distance: 9.5},
			{name: "Budds Lake", distance: 8.1},
			{name: "Chatham", distance: 10.7},
			{name: "Chester", distance: 6.7},
			{name: "Denville", distance: 9.5},
			{name: "Dover", distance: 3.7},
			{name: "Drakestown", distance: 10.7},
			{name: "Flanders", distance: 5.9},
			{name: "German Valley", distance: 10.6},
			{name: "Green Village", distance: 8.1},
			{name: "Hackettstown", distance: 12.5},
			{name: "Hanover", distance: 10.1},
			{name: "Hibernia", distance: 8.9},
			{name: "Hurdtown", distance: 9.1},
			{name: "Madison", distance: 8.9},
			{name: "Mendham", distance: 3.8},
			{name: "Milton", distance: 12.7},
			{name: "Montville", distance: 11.8},
			{name: "Morristown", distance: 5.0},
			{name: "New Vernon", distance: 6.3},
			{name: "Parsippany", distance: 8.6},
			{name: "Pompton Plains", distance: 16.8},
			{name: "Port Oram", distance: 4.4},
			{name: "Rockaway", distance: 5.5},
			{name: "Schooleys Mountain", distance: 12.0},
			{name: "Shippenport", distance: 6.2},
			{name: "Stanhope", distance: 8.1},
			{name: "Stephensburgh", distance: 15.7},
			{name: "Succasunny", distance: 3.8}}},

		{name: "Waterville", dist: []place{
			{name: "Beavertown", distance: 15.1},
			{name: "Boonton", distance: 10.2},
			{name: "Budds Lake", distance: 9.3},
			{name: "Chatham", distance: 9.4},
			{name: "Chester", distance: 6.8},
			{name: "Denville", distance: 7.5},
			{name: "Dover", distance: 5.5},
			{name: "Drakestown", distance: 11.0},
			{name: "Flanders", distance: 7.1},
			{name: "German Valley", distance: 10.9},
			{name: "Green Village", distance: 6.6},
			{name: "Hackettstown", distance: 13.4},
			{name: "Hanover", distance: 9.5},
			{name: "Hibernia", distance: 10.4},
			{name: "Hurdtown", distance: 11.1},
			{name: "Madison", distance: 7.6},
			{name: "Mendham", distance: 2.7},
			{name: "Milton", distance: 14.4},
			{name: "Montville", distance: 12.4},
			{name: "Morristown", distance: 4.1},
			{name: "New Vernon", distance: 4.4},
			{name: "Parsippany", distance: 8.6},
			{name: "Pompton Plains", distance: 17.6},
			{name: "Port Oram", distance: 6.3},
			{name: "Rockaway", distance: 7.0},
			{name: "Schooleys Mountain", distance: 12.5},
			{name: "Shippenport", distance: 7.9},
			{name: "Stanhope", distance: 9.7},
			{name: "Stephensburgh", distance: 15.7},
			{name: "Succasunny", distance: 5.5},
			{name: "Walnut Grove", distance: 7.9}}},

		{name: "Whippany", dist: []place{
			{name: "Beavertown", distance: 8.4},
			{name: "Boonton", distance: 5.3},
			{name: "Budds Lake", distance: 16.0},
			{name: "Chatham", distance: 5.2},
			{name: "Chester", distance: 14.4},
			{name: "Denville", distance: 5.5},
			{name: "Dover", distance: 8.2},
			{name: "Drakestown", distance: 18.1},
			{name: "Flanders", distance: 13.9},
			{name: "German Valley", distance: 18.4},
			{name: "Green Village", distance: 5.6},
			{name: "Hackettstown", distance: 20.5},
			{name: "Hanover", distance: 2.3},
			{name: "Hibernia", distance: 8.9},
			{name: "Hurdtown", distance: 12.1},
			{name: "Madison", distance: 4.1},
			{name: "Mendham", distance: 10.1},
			{name: "Milton", distance: 13.5},
			{name: "Montville", distance: 6.7},
			{name: "Morristown", distance: 3.6},
			{name: "New Vernon", distance: 6.4},
			{name: "Parsippany", distance: 2.9},
			{name: "Pompton Plains", distance: 11.5},
			{name: "Port Oram", distance: 9.5},
			{name: "Rockaway", distance: 7.0},
			{name: "Schooleys Mountain", distance: 20.0},
			{name: "Shippenport", distance: 13.0},
			{name: "Stanhope", distance: 15.4},
			{name: "Stephensburgh", distance: 23.2},
			{name: "Succasunny", distance: 11.2},
			{name: "Walnut Grove", distance: 8.0},
			{name: "Waterville", distance: 7.6}}},
	}
	deck := generate.NewSlides(os.Stdout, 0, 0)
	deck.StartDeck()
	deck.StartSlide()
	deck.Text(40, 95, "TABLE OF DISTANCES", "sans", 3, "gray")
	deck.Text(40, 89, "MORRIS COUNTY, NEW JERSEY", "serif", 3.5, "")
	deck.TextBlock(40, 85, "Showing the distance in miles and tenths, in an air line from one place to another", "serif", 1.5, 50, "gray")

	distable(deck, data, 1, 90, 1.1)
	deck.EndSlide()
	deck.EndDeck()

}

func distable(deck *generate.Deck, table []dt, left, top, size float64) {

	distleft := left + (size * 12)
	x := distleft - size
	y := top
	vspacing := size * 2.4
	hspacing := size * 2.4
	for _, t := range table {
		deck.TextRotate(x, y-vspacing, t.name, "", "serif", 90, size, "")
		deck.Line(x-size-0.2, y-1, x-size-0.2, 2, 0.05, "gray")
		x += hspacing
		y -= vspacing
	}

	x = left
	y = top - vspacing
	for _, t := range table {
		deck.Text(x, y, t.name, "serif", size, "")
		dx := distleft
		dy := y

		for _, d := range t.dist {
			td := strconv.FormatFloat(d.distance, 'f', 1, 64)
			deck.TextEnd(dx, dy, td, "mono", size, "")
			//deck.Rect(dx-size, dy+size/2, size+hspacing/2, size+vspacing*0.4, "red", 10)
			dx += hspacing
		}
		deck.Line(distleft-size*2, y-1, dx+0.2, y-1, 0.05, "gray")
		y -= vspacing
	}
}
